# Generated by Django 4.1.7 on 2023-02-24 20:22

from django.db import migrations, models
import payment_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, verbose_name='maxsulot nomi')),
                ('desc', models.TextField(verbose_name='tasnifi')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='narxi')),
                ('thumbnail', models.ImageField(blank=True, upload_to=payment_app.models.get_image_filename)),
            ],
            options={
                'verbose_name': 'Maxsulot',
                'verbose_name_plural': 'Maxsulotlar',
                'ordering': ['name'],
            },
        ),
    ]
